config/routes.rb
Teamprofile::Application.routes.draw do
  resources :companies, only: [:index, :show]
  resources :job_titles, only: [:index, :show]
  resources :groups
  resources :group_members, only: [:create, :destroy]
  resources :personality_types, only: [:show, :index]
  resources :quiz, only: [:show]
  resources :tips, only: [:show, :create, :destroy, :update]
  resources :tip_votes, only: [:create, :destroy]
  resources :users
  resources :user_answers, only: [:index, :create]

  resource :session

  get '_',    to: 'static_pages#empty', as: 'empty'

  get 'support',  to: 'static_pages#support'
  get 'home',     to: 'static_pages#home'
  get 'how',      to: 'static_pages#how'
  get 'privacy',  to: 'static_pages#privacy'
  get 'terms',    to: 'static_pages#terms'

  match 'auth/:provider/callback' => 'sessions#create_from_linkedin'
  match 'signout', to: 'sessions#destroy', as: 'signout'
  root to: "static_pages#landing"
end

app/models/user.rb
class User < ActiveRecord::Base
  # serialize :description, JSON
  serialize :connections, JSON

  attr_accessible :name, :uid, :provider, :email, :description, :headline, :image_url, :location, :industry, :pub_profile, :access_token, :access_token_secret, :session_token, :password_digest, :password, :password_confirmation, :personality_type_id, :connections, :referral_hash

  before_validation :set_password_digest, on: :create
  before_validation :set_referral_hash, on: :create
  
  validate :password_matches_confirmation

  has_many :user_answers
  has_many :answers, through: :user_answers

  has_many :sent_invitations,     foreign_key: :from_user_id, class_name: "Invitation"
  has_many :received_invitations, foreign_key: :to_user_id,   class_name: "Invitation"

  has_many :invited_users,  through: :sent_invitations, source: :receiving_user
  has_many :inviting_users, through: :received_invitations, source: :sending_user

  has_many :group_memberships, class_name: "GroupMember"
  has_many :groups, through: :group_memberships

  has_many :authored_tips, foreign_key: :author_user_id, class_name: "Tip"

  # this is the GENERAL personality type (INTJ, ENFP, etc.)
  belongs_to :personality_type

  belongs_to :company
  belongs_to :job_title

  # this is the customized personality type that can be modified for a specific user
  has_one    :custom_personality

  attr_accessor :password, :password_confirmation

  def self.from_omniauth(auth_hash)
    user        = User.where(uid: auth_hash["uid"]).first_or_initialize

    # IMPORTANT: make this !user.account_active when done testing!!!!!
    new_account = !user.account_active

    user.account_active       = true
    user.uid                  = auth_hash["uid"]
    user.provider             = auth_hash["provider"]
    user.access_token         = auth_hash["credentials"]["token"]
    user.access_token_secret  = auth_hash["credentials"]["secret"]
    user.name                 = auth_hash["info"]["name"]
    user.email                = auth_hash["info"]["email"]
    user.location             = auth_hash["info"]["location"]
    user.headline             = auth_hash["info"]["headline"]
    user.industry             = auth_hash["info"]["industry"]
    user.image_url            = auth_hash["info"]["image"]
    user.pub_profile          = auth_hash["info"]["urls"]["public_profile"]

    user.custom_personality   ||= CustomPersonality.new

    user.save!
    UserMailer.delay.welcome_email(user) if new_account

    
    user.get_large_image_url
    user.set_job_title_and_company

    user
  end

  def set_job_title_and_company
    split_headline = self.headline.split(" at ")
    job_title      = split_headline.first
    company        = split_headline.last if split_headline.length > 1

    self.job_title = JobTitle.find_by_name(job_title) || JobTitle.new(name: job_title)
    self.company   = Company.find_by_name(company) || Company.new(name: company) if company
    self.save
  end
  handle_asynchronously :set_job_title_and_company

  def self.find_by_credentials(params={email: nil, password: nil})
    user = User.find_by_email(params[:email]);
    return user if user && user.is_password?(params[:password])
    nil
  end

  def editable_tip_ids
    (self.authored_tip_ids + self.custom_personality.tip_ids).uniq
  end

  def get_large_image_url
    self.large_image_url = self.linkedin.picture_urls.all.first
    self.save
  end
  handle_asynchronously :get_large_image_url

  def num_sent_invitations
    self.sent_invitations.length
  end


  def valid_connection_ids
    return @valid_ids if @valid_ids
    return [] if !self.connections

    @valid_ids = [self.id]
    # load all connection IDs

    @valid_ids = self.connections.map {|c| c["id"]}

    # load all connections in groups
    @valid_ids += self.groups.includes(:members).map(&:member_ids)
    @valid_ids += self.invited_user_ids

    # puts "\n"*10
    # puts "got here"
    # puts "\n"*10
    @valid_ids = @valid_ids.flatten.uniq
  end

  def build_shadow_accounts
    # reset connections since they will be rebuilt
    self.connections        = []    
    start = 0
    batch_size = 500

    loop do
      linkedin_connects = self.linkedin.connections(start: start, count: batch_size)["all"]
      break if linkedin_connects.nil?
      build_batch(linkedin_connects)
      start += batch_size
    end

    self.connections = self.connections.uniq
    self.save
    self.ensure_profile_available
  end

  def ensure_profile_available
    ActiveRecord::Base.transaction do
      connected_users = User.where(id: self.valid_connection_ids, account_active: true)
      connection_info = self.connections.find { |c| c["name"] == self.name }
      connected_users.each do |user|
        if !user.connections.include?(connection_info)
          user.connections << connection_info
          user.save
        end
      end
    end
  end
  handle_asynchronously :ensure_profile_available

  def build_batch(linkedin_connects)
    linkedin_connects_uids  = linkedin_connects.map {|c| c["id"]}

    # "Existing" means users who are already in the database and match the current user's connections' uids
    existing_users_assn     = User.where(uid: linkedin_connects_uids)
    existing_users_hash     = {}
    existing_users_assn.each {|u| existing_users_hash[u.uid] = u}


    ActiveRecord::Base.transaction do 
      linkedin_connects.each do |connection|
        uid                 = connection["id"]
        user                = existing_users_hash[uid]
        valid_user          = true
        if !user
        # user = User.where(uid: uid).first_or_initialize
          user              = User.new
          user.pub_profile  = clean { connection["site_standard_profile_request"]["url"].split("&").first }
          user.name         = clean { connection["first_name"] + " " + connection["last_name"] }
          user.headline     = clean { connection["headline"] }
          user.industry     = clean { connection["industry"] }
          user.location     = clean { connection["location"]["name"] }
          user.image_url    = clean { connection["picture_url"] }
          user.uid          = clean { connection["id"] }
          valid_user        = user.uid && user.name && user.name != "private private"

          user.custom_personality = CustomPersonality.new
          if valid_user
            user.save
            user.set_job_title_and_company
          end
        end
        self.connections << {name: user.name, image_url: user.image_url, id: user.id} if valid_user
      end
      self.connections << {name: self.name, image_url: self.image_url, id: self.id}
      self.save
    end
  end

  def clean
    begin
      yield
    rescue
      nil
    end
  end

  def send_completion_notification
    users_to_contact      = self.inviting_users.includes(:groups)

    valid_connection_ids  = self.connections.map {|c| c["id"]}

    connected_users       = User.includes(:groups).where(account_active: true, id: valid_connection_ids)

    users_to_contact      += connected_users

    # just send Sol an email every time someone completes the assessment
    users_to_contact << User.find_by_name("Sol Garger")

    users_to_contact      = users_to_contact.uniq

    shared_groups         = Hash.new { |h, k| h[k] = [] }

    users_to_contact.each do |u|
      shared_groups[u.id] = u.groups & self.groups
    end

    # p shared_groups

    # puts users_to_contact.map(&:id)

    puts "\n"*10
    users_to_contact.each do |u|
      next if u == self
      puts "shared groups for user id #{u.id} is: #{shared_groups[u.id].inspect}"
      # puts "\n"
      msg = UserMailer.invitee_profile_completion(
              inviting_user: u, 
              invited_user: self, 
              shared_groups: shared_groups[u.id]
            )
      msg.deliver
    end
    puts "\n"*10
  end
  handle_asynchronously :send_completion_notification

  def set_personality_type
    first_test_attempt = self.personality_type_id.nil?

    results_str = ""
    self.mbti_test_result.each do |result|
      # p "result is #{result.last.class}"
      results_str += result.last > 0 ? result[0][0] : result[0][1]
    end

    personality_type = PersonalityType.find_by_title(results_str.upcase)
    self.personality_type_id = personality_type.id

    self.custom_personality ||= CustomPersonality.new

    self.custom_personality.add_defaults(personality_type)

    self.send_completion_notification if first_test_attempt
    self.save
  end


  def mbti_test_result
    return @results_arr if @results_arr

    results_hash = Hash.new {|h, k| h[k] = 0}

    self.answers.each do |answer|
      answer_result     = answer.result_calc
      key               = answer_result.keys.first
      results_hash[key] += answer_result[key]
    end

    results_ordering = {"ei"=>0, "sn"=>1, "tf"=>2, "jp"=>3}

    @results_arr = results_hash.to_a.sort do |a, b|
      results_ordering[a.first] <=>  results_ordering[b.first]
    end
    @results_arr
  end 

  def set_session_token
    self.session_token = SecureRandom.urlsafe_base64(16);
  end

  def set_referral_hash
    self.referral_hash = SecureRandom.urlsafe_base64(8);
  end

  def reset_session_token!
    set_session_token
    save!
  end

  def set_password_digest
    self.password_digest = BCrypt::Password.create(self.password) if self.password
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def linkedin
    @client ||= LinkedIn::Client.new(ENV["LINKEDIN_KEY"], ENV["LINKEDIN_SECRET"])
    @client.authorize_from_access(self.access_token, self.access_token_secret)
    @client
  end

  def password_matches_confirmation
    if self.password && self.password != self.password_confirmation
      errors.add(:password, "password does not match confirmation")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, only: [:show, :new, :create]

  # remove this in production
  def index
    render json: {user: current_user}
    # redirect_to empty_url(anchor: 'groups')
  end

  def show
    if !current_user
      @user = User.includes(
                      :personality_type, 
                      :sent_invitations, 
                      :groups => [:members], 
                      :custom_personality => [:tips => [:tip_votes, :author]]
                      ).find(params[:id])

      # TODO: do not repeat this.
      @manager_tips   = @user.custom_personality.tips.shuffle.select { |tip| tip.relationship_type == "as_manager"   }
      @colleague_tips = @user.custom_personality.tips.shuffle.select { |tip| tip.relationship_type == "as_colleague" }
      @employee_tips  = @user.custom_personality.tips.shuffle.select { |tip| tip.relationship_type == "as_employee"  }

      render 'show_public.html.erb'
    else
      params[:id] = current_user.id if params[:id] == "dummy"
      params[:id] = current_user.id if params[:id] == "current"
      
      user_id     = params[:id].to_i
      # puts "current user id is #{current_user.id}"
      if user_id == current_user.id
        # puts "\n"*5
        # puts "fetching current user"
        # puts "\n"*5
        @user = User.includes(
                              :personality_type, 
                              :sent_invitations, 
                              :groups => [:members], 
                              :custom_personality => [:tips => [:tip_votes, :author]]
                              ).find(current_user.id)

        # @manager_tips   = @user.custom_personality.tips.select { |tip| tip.relationship_type == "as_manager"   }
        # @colleague_tips = @user.custom_personality.tips.select { |tip| tip.relationship_type == "as_colleague" }
        # @employee_tips  = @user.custom_personality.tips.select { |tip| tip.relationship_type == "as_employee"  }

        respond_to do |format|
          format.html { redirect_to empty_url(anchor: "users/#{params[:id]}") }
          format.json { render 'show.json.jbuilder' }
        end

      # elsif current_user.valid_connection_ids.include?(user_id)
      elsif User.find(user_id)
        # puts "\n"*5
        # puts "fetching other user"
        # puts "\n"*5
        @user = User.includes(
                              :personality_type, 
                              :custom_personality => [:tips => [:tip_votes, :author]]
                              ).find(user_id)
        # at some point only pull down a limited set of results
        respond_to do |format|
          format.html { redirect_to empty_url(anchor: "users/#{params[:id]}") }
          format.json { render 'show_other.json.jbuilder' }
        end
      else
        # puts "\n"*5
        # puts "user is not valid"
        # puts user_id
        # puts current_user.id
        # puts "\n"*5
        # render status: 500
        head :bad_request
      end
    end
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      log_in! @user
      render json: @user
    else
      flash[:errors] = @user.errors.full_messages
      @user = User.new(params[:user])
      render :new
    end
  end

  def update
    # params.delete("connections")
    # params.delete("user")
    # # puts "\n"*5
    # # puts params.keys.sort
    # # puts "\n"*5
    # # puts "build_shadow: #{params[:build_shadow]}"
    # # puts "async: #{params[:async]}"


    if params[:build_shadow] && (params[:async] == true)
      # # puts "\n"*5
      # # puts "ASYNC: building shadow accounts"
      # # puts "\n"*5

      current_user.delay.build_shadow_accounts
      @user = current_user
      render 'show.json.jbuilder'
    elsif params[:build_shadow] && (params[:async] == false)
      # # puts "\n"*5
      # # puts "SYNCHRONOUS: building shadow accounts"
      # # puts "\n"*5

      current_user.build_shadow_accounts
      @user = current_user
      render 'show.json.jbuilder'
    else
      # # puts "\n"*5
      # # puts "NOT BUILDING SHADOW ACCOUNTS"
      # # puts "\n"*5

      @user = User.find(params[:id])
      if @user.update_attributes(params[:user])
        # log_in! @user
        render json: @user
      else
        flash[:errors] = @user.errors.full_messages
        @user = User.new(params[:user])
        render :new
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    render json: @user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<a href="/auth/linkedin">Sign Up with LinkedIn</a>

<br>
OR create a new account manually
<hr>

<form action="<%= users_url %>" method="POST">
  <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />

  <label for="user_name">Full Name</label>
  <input type="text" name="user[name]" id="user_name" value="<%= @user.name %>">

  <label for="user_email">Email</label>
  <input type="text" name="user[email]" id="user_email" value="<%= @user.email %>">

  <label for="user_password">Password</label>
  <input type="password" name="user[password]" id="user_password" value="<%= @user.password %>">

  <label for="user_password_confirmation">Password-Confirmation</label>
  <input type="password" name="user[password_confirmation]" id="user_password_confirm" value="<%= @user.password_confirmation %>">

  <input type="submit" value="Log In">
</form>

app/views/users/show.html.erb
showing a user page!

app/views/users/show_public.html.erb
<% @title = "#{@user.name} | Minzio. Myers Briggs Personality profile" %> 
<% @description = "View #{@user.name}'s personality profile on Minzio. Minzio provides a myers briggs personality assessment test, tips for working with Jennifer Byrne and other professionals of any personality type" %>

<div id="content"><div>
  <div class="user user-public">
    <div class="row">
      <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
        <div class="user-basic-info">
          <div>
            <div class="content-container">
              <div class="row content-area"> 
                <div class="col-xs-5 col-sm-4 col-md-4">
                  <div class="user-top">

                    <img src="/default_user.png" class="user-image">

                  </div>

                </div>
                <div class="col-xs-6 col-sm-6 col-md-8">
                  <h1>
                    <div class="profile-item user-name">
                      <%= @user.name %>
                    </div>
                  </h1>

                  <h2>
                    <div class="profile-item">
                      <%= @user.headline %>
                    </div>
                  </h2>
                  <h4>
                    <div class="profile-item">
                      <%= @user.industry %>
                    </div>
                  </h4>
                  <h4>
                    <div class="profile-item">
                      <%= @user.location %>
                    </div>
                  </h4>
                  <% if @user.pub_profile %>
                  <div class="profile-item">
                    <a href="<%= @user.pub_profile %>" target="blank">LinkedIn profile</a>
                  </div>
                  <% end %>
                  <br>
                </div>
                <div class="col-xs-12">
                  <div class="pub-profile-notice">
                    <div class="join-message">
                      Join Minzio and access <%= @user.name %>'s full profile. It's free!
                    </div>
                    As a Minzio member, you get access to:
                    <ul>
                      <li>Each of of the tips below, ranked by <%= @user.name %>'s LinkedIn connections</li>
                      <li>Detailed recommendations on working with each of your colleagues</li>
                      <li>A proprietary workplace personality assessment</li>
                    </ul>
                    <div class="view-full-profile-btn-container">
                      <a href="/auth/linkedin">
                        <btn class="btn btn-warning">View full profile</btn>
                      </a>
                    </div>
                    <br>
                  </div>
                </div>

              </div>
            </div>
          </div>
        </div>
        <br>

        <div class="row">
          <div class="content-container">
            <div class="content-area personality-column">
              <div class="working-with-personality">
                <div>
                  <div class="pub-profile-section-header">
                    <h2>Working with <%= @user.name %></h2>
                  </div>
                  <br>
                  <div class="colleague-type">
                    As a colleague
                  </div>
                  <table class="table">
                    <% @colleague_tips.each do |tip| %>
                    <tr>
                      <td class="tip">
                        <%= tip.text %>
                      </td>
                    </tr>
                    <% end %>
                  </table>

                  <br>
                  <div class="colleague-type">
                    As an employee
                  </div>
                  <table class="table">
                    <% @employee_tips.each do |tip| %>
                    <tr>
                      <td class="tip">
                        <%= tip.text %>
                      </td>
                    </tr>
                    <% end %>
                  </table>
                  <br>
                  <div class="colleague-type">
                    As a manager
                  </div>
                  <table class="table">
                    <% @manager_tips.each do |tip| %>
                    <tr>
                      <td class="tip">
                        <%= tip.text %>
                      </td>
                    </tr>
                    <% end %>
                  </table>
                </div>
                <!-- </table> -->
              </div>

            </div>
          </div>
        </div>
        <% if @user.personality_type_id %>
        <div class="content-container">
          <div class="row content-area">
            <div class="col-xs-12">
              <div class="personality-type">
                <%= @user.personality_type.title %>
              </div>
              <div class="long-personality-type">
                <%= @user.personality_type.small_info %>
              </div>
              <div class="personality-info lead">
                <%= @user.personality_type.large_info.html_safe %>
              </div>

            </div>
          </div>
        </div>
        <br>
        <% end %>
        <div>
          <% if @user.company_id %>
          <div>
            <a href="/companies/<%= @user.company_id %>">
              <%= @user.company.name %> employees
            </a>
          </div>
          <% end %>

          <% if @user.job_title_id %>
          <div>
            <a href="/job_titles/<%= @user.job_title_id %>">
              <%= @user.job_title.name %> professionals
            </a>
          </div>
          <% end %>
        </div>
      </div>
    </div>