config/routes.rb
Teamprofile::Application.routes.draw do
  resources :companies, only: [:index, :show]
  resources :job_titles, only: [:index, :show]
  resources :groups
  resources :group_members, only: [:create, :destroy]
  resources :personality_types, only: [:show, :index]
  resources :quiz, only: [:show]
  resources :tips, only: [:show, :create, :destroy, :update]
  resources :tip_votes, only: [:create, :destroy]
  resources :users
  resources :user_answers, only: [:index, :create]

  resource :session

  get '_',    to: 'static_pages#empty', as: 'empty'

  get 'support',  to: 'static_pages#support'
  get 'home',     to: 'static_pages#home'
  get 'how',      to: 'static_pages#how'
  get 'privacy',  to: 'static_pages#privacy'
  get 'terms',    to: 'static_pages#terms'

  match 'auth/:provider/callback' => 'sessions#create_from_linkedin'
  match 'signout', to: 'sessions#destroy', as: 'signout'
  root to: "static_pages#landing"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,900' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="initial-scale = 1.0,maximum-scale = 1.0"/>
  
  <meta name="msvalidate.01" content="4BB84097EF445C57C0E10E89EDA6E8E1" />

  <!-- for Google -->
  <meta name="description" content="<%= @description %>" />
  <meta name="keywords" content="minzio, free, personality profile, personality type, personality, test, personality quiz, career test, jung test, peronality assessment, myers briggs" />

  <meta name="copyright" content="2014" />
  <meta name="application-name" content="Minzio" />

  <!-- for Facebook -->
  <!-- <meta property="og:title" content="Minzio: Personality Profiles for the Workplace"/> -->
  <meta property="og:url" content="http://www.minzio.com"/>
  <meta property="og:site_name" content="Minzio"/>
  <meta property="og:type" content="website"/>
  <meta property="og:description" content="free Jungian personality assessment for the workplace. Minzio's career test is based on decades of research, and is fully integrated with LinkedIn for easy sharing with colleagues"/>
  <meta property="og:image" content="/sea_green_robot_only.png"/>
<!-- the og:image:type property isn’t strictly necessary.  put the extension of your facebook image here -->
  <meta property="og:image:type" content="image/png"/>

  <!-- for Twitter -->          
<!--   <meta name="twitter:card" content="summary" />
  <meta name="twitter:site" content="@yourtwitterhandle"/>
  <meta name="twitter:title" content="your product name" />
  <meta name="twitter:description" content="your product description" />
  <meta name="twitter:image" content="your image url" />
 -->
 <script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "8a0c1e8a-2e40-49ef-a543-b780be92c7c4", doNotHash: true, doNotCopy: false, hashAddressBar: false});</script>

</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" id="top-nav">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="/">
              <!-- Minzio -->
              <img src="/minzio_white.png" class="brand">
            </a>

          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
              <li id="user-search-nav" class="top-nav-link">
              </li>

              <li id="profile-nav">
                <a href="<%= "#users/#{current_user.id}" %>" class="top-nav-link top-nav-img-link">
                  <img src="<%= current_user.image_url %>" class="nav-img ">  <%= current_user.name.split.first %>
                </a>
              </li>


              <li id="groups-nav">
                <%= link_to "Groups", "#groups", class: "top-nav-link" %>
              </li>

              <li id="test-nav">
                <%= link_to "Personality Test", "#assessment", class: "top-nav-link" %>
              </li>

              <li>
                <%= link_to("Log Out", signout_path, class: "top-nav-link")%>
              </li>
              <% else %>
              <li>
                <%= link_to("Already a member?", "/auth/linkedin", class: "top-nav-link")%>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </nav>

  <div class="container-fluid">
    <div class="row">
    </div>
    <div id="content">
      <%= yield %>
    </div>
  </div>  

  <!-- <hr> -->
  <div class="footer">
    <div class="footer-content">
      <span class="footer-item">
        <a href="/how">how it works</a>
      </span>
<!--       <span class="footer-item">
        <a href="#/contact">contact</a>
      </span>
 -->      <span class="footer-item">
        <a href="/terms">terms of service</a>
      </span>
      <span class="footer-item">
        <a href="/privacy">privacy</a>
      </span>
      <span class="footer-item">
        <a href="/support">support</a>
      </span>

      <span class="footer-item">
        <span class="glyphicon glyphicon-twitter"></span>
        <span class="glyphicon glyphicon-facebook"></span>
      </span>
    </div>
    <br>
    <div class="footer-content">
      <span class="footer-item">
        <a href="/companies" rel="canonical">professionals by company</a>
      </span>
      <span class="footer-item">
        <a href="/job_titles" rel="canonical">professionals by job title</a>
      </span>

    </div>
  </div>

</body>
</html>